Category.create({"cat" => "age", "name"=> 'Children (0-18)'})
Category.create({"cat" => "age", "name"=> 'Adults (18-65)'})
Category.create({"cat" => "age", "name"=> 'Seniors (65+)'})

Category.create({"cat" => "bpv", "name"=> 'Biological and physiological variables'})

Category.create({"cat" => "disease", "name"=> 'Certain infections and parasitic Diseases and related symptoms'})
Category.create({"cat" => "disease", "name"=> 'Neoplasms and related symptoms'})
Category.create({"cat" => "disease", "name"=> 'Diseases of and symptoms related to the blood and blood-forming organs and certain disorders involving the immune mechanism'})
Category.create({"cat" => "disease", "name"=> 'Endocrine, nutritional and metabolic Diseases and related symptoms'})
Category.create({"cat" => "disease", "name"=> 'Mental and behavioural disorders and related symptoms'})
Category.create({"cat" => "disease", "name"=> 'Diseases of and symptoms related to the nervous system'})
Category.create({"cat" => "disease", "name"=> 'Diseases of and symptoms related to the eye and adnexa'})
Category.create({"cat" => "disease", "name"=> 'Diseases of and symptoms related to the ear and mastoid process'})
Category.create({"cat" => "disease", "name"=> 'Diseases of and symptoms related to the circulatory system'})
Category.create({"cat" => "disease", "name"=> 'Diseases of and symptoms related to the respiratory system'})
Category.create({"cat" => "disease", "name"=> 'Diseases of and symptoms related to the digestive system'})
Category.create({"cat" => "disease", "name"=> 'Diseases of and symptoms related to the skin and subcutaneous tissue'})
Category.create({"cat" => "disease", "name"=> 'Diseases of and symptoms related to the musculoskeletal system and connective tissue'})
Category.create({"cat" => "disease", "name"=> 'Diseases of and symptoms related to the genitourinary system'})
Category.create({"cat" => "disease", "name"=> 'Pregnancy, childbirth and puerperium and related symptom'})
Category.create({"cat" => "disease", "name"=> 'Certain conditions originating in the perinatal period and related symptoms'})
Category.create({"cat" => "disease", "name"=> 'Congenital malformations, deformations and chromosomal abnormalities and related symptoms'})
Category.create({"cat" => "disease", "name"=> 'Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified'})
Category.create({"cat" => "disease", "name"=> 'Injury, poisoning and certain other consequences of external causes'})
Category.create({"cat" => "disease", "name"=> 'External causes of morbidity and mortality'})
Category.create({"cat" => "disease", "name"=> 'Factors influencing health status and contact with health services'})
Category.create({"cat" => "disease", "name"=> 'Codes for special purposes'})

Category.create({"cat" => "fs", "name"=> 'Physical functioning'})
Category.create({"cat" => "fs", "name"=> 'Cognitive/mental functioning'})
Category.create({"cat" => "fs", "name"=> 'Social functioning'})
Category.create({"cat" => "fs", "name"=> 'Role functioning'})

Category.create({"cat" => "ghp", "name"=> 'Self-rated health'})
Category.create({"cat" => "ghp", "name"=> 'Health-related QoL'})

Category.create({"cat" => "oql", "name"=> 'Overall QoL'})

Category.create({"cat" => "pnp", "name"=> 'Patient-reported outcome'})
Category.create({"cat" => "pnp", "name"=> 'Non-patient-reported outcome'})

Category.create({"cat" => "ss", "name"=> 'Physical state'})
Category.create({"cat" => "ss", "name"=> 'Emotional state'})
Category.create({"cat" => "ss", "name"=> 'Cognitive/mental state'})

Category.create({"cat" => "tmi", "name"=> '1 - Questionnaire'})
Category.create({"cat" => "tmi", "name"=> '2 - Interviews'})
Category.create({"cat" => "tmi", "name"=> '3 - Diaries'})
Category.create({"cat" => "tmi", "name"=> '4 - Performance based tests'})
Category.create({"cat" => "tmi", "name"=> '5 - Videos'})
Category.create({"cat" => "tmi", "name"=> '6 - Clinical rating scales'})
Category.create({"cat" => "tmi", "name"=> '7 - Observations'})
Category.create({"cat" => "tmi", "name"=> '8 - Imaging tests'})
Category.create({"cat" => "tmi", "name"=> '9 - Laboratory tests'})

Category.create({"cat" => "status", "name"=> 'new'})
Category.create({"cat" => "status", "name"=> 'in review'})
Category.create({"cat" => "status", "name"=> 'published'})
